#!/usr/bin/env bash

check_factor() {
    if [ $# -ne 2 ]; then
        return
    fi

    num1=$1
    num2=$2

    if ((num2 > num1)); then
        numcp=$num1
        num1=$num2
        num2=$numcp
    fi

    num=$(echo "$num1 * $num2" | bc)
    echo "$num1=$num2*$num"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
fi

while IFS= read -r number; do
    factors=$(factor "$number")
    check_factor $factors
done < "$1"

