#!/usr/bin/python3

import sys

def smallest_divisor(num: int) -> int:

    while num % 2 == 0:
        return 2

    factor = 3
    while factor * factor <= num:
        if num % factor == 0:
            return factor
        else:
            factor += 2

    return 1


def factor():

    with open(sys.argv[1]) as f:
        line = f.readline()
        while line != '':
            num = int(line)
            div = smallest_divisor(num)
            print(f"{num}={num//div}*{div}")

            line = f.readline()


if __name__ == "__main__":
    (factor)
